blog/urls.py
from django.urls import path

from .views import index, get_article, get_articles_by_tag, \
                    get_results, get_random_article, get_articles_by_user, CreateArticle

app_name = 'blog'

urlpatterns = [
    path('', index, name='home'),
    path('creator/<str:username>', get_articles_by_user, name='get_articles_by_user'),
    path('new_article/', CreateArticle.as_view(), name='create_article'),
    path('article/<str:slug>', get_article, name='get_article'),
    path('random/', get_random_article, name='random_article'),
    path('search/', get_results, name='search'),
    path('tag/<str:slug>', get_articles_by_tag, name='get_articles_by_tag'),
]

blogapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .settings import DEBUG

urlpatterns = [
    path('', include('blog.urls')),
    path('user/', include('user.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('captcha/', include('captcha.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if DEBUG:
    # на винде маймтайпы тупят
    import mimetypes

    mimetypes.add_type("application/javascript", ".js", True)
    urlpatterns.append(path('admin/', admin.site.urls))
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))

user/urls.py
from django.urls import path

from .views import sign_up, sign_in, log_out

app_name = 'user'

urlpatterns = [
    path('sign_up/', sign_up, name='sign_up'),
    path('sign_in/', sign_in, name='sign_in'),
    path('logout/', log_out, name='logout'),
]

templates/includes/_footer.html
{% load static %}
{% load tags %}
{% popular_posts as posts %}
{% article_tags as tags %}
{% popular_users as creators %}

<div class="container-fluid fh5co_footer_bg pb-3">
    <div class="container animate-box">
        <div class="row">
            <div class="col-12 spdp_right py-5"><img src="{% static 'images/white_logo.png' %}" alt="img" class="footer_logo"/></div>
            <div class="clearfix"></div>
            <div class="col-12 col-md-4 col-lg-3">
                <div class="footer_main_title py-3"> About</div>
                <div class="footer_sub_about pb-3"> My first site for news
                </div>
                <div class="footer_mediya_icon">
                    <div class="text-center d-inline-block"><a class="fh5co_display_table_footer">
                        <div class="fh5co_verticle_middle"><i class="fa fa-linkedin"></i></div>
                    </a></div>
                    <div class="text-center d-inline-block"><a class="fh5co_display_table_footer">
                        <div class="fh5co_verticle_middle"><i class="fa fa-google-plus"></i></div>
                    </a></div>
                    <div class="text-center d-inline-block"><a class="fh5co_display_table_footer">
                        <div class="fh5co_verticle_middle"><i class="fa fa-twitter"></i></div>
                    </a></div>
                    <div class="text-center d-inline-block"><a class="fh5co_display_table_footer">
                        <div class="fh5co_verticle_middle"><i class="fa fa-facebook"></i></div>
                    </a></div>
                </div>
            </div>
            <div class="col-12 col-md-3 col-lg-2">
                <div class="footer_main_title py-3"> Category</div>
                <ul class="footer_menu">
                    {% for tag in tags|slice:'5' %}
                        <li>
                            <a href="{{ tag.get_absolute_url }}" class=""><i class="fa fa-angle-right"></i>&nbsp;&nbsp; {{ tag.title }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-12 col-md-5 col-lg-3 position_footer_relative">
                <div class="footer_main_title py-3"> Most Viewed Posts</div>
                {% for post in posts|slice:'4' %}
                    <div class="footer_makes_sub_font"> {{ post.created_at }}</div>
                    <a href="{% url 'blog:get_article' post.slug %}" class="footer_post pb-4"> {{ post.title|truncatechars:50 }}</a>
                {% endfor %}
                <div class="footer_position_absolute"><img src="{% static 'images/footer_sub_tipik.png' %}" alt="img" class="width_footer_sub_img"/></div>
            </div>
            <div class="col-12 col-md-12 col-lg-4 ">
                <div class="footer_main_title py-3"> Popular Creators</div>
                {% for creator in creators %}
                    <a href="{% url 'blog:get_articles_by_user' creator.username %}">{{ creator.username }}</a>
                {% endfor %}
            </div>
        </div>
{#        <div class="row justify-content-center pt-2 pb-4">#}
{#            <div class="col-12 col-md-8 col-lg-7 ">#}
{#                <div class="input-group">#}
{#                    <span class="input-group-addon fh5co_footer_text_box" id="basic-addon1"><i class="fa fa-envelope"></i></span>#}
{#                    <input type="text" class="form-control fh5co_footer_text_box" placeholder="Enter your email..." aria-describedby="basic-addon1">#}
{#                    <a href="#" class="input-group-addon fh5co_footer_subcribe" id="basic-addon12"> <i class="fa fa-paper-plane-o"></i>&nbsp;&nbsp;Subscribe</a>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
    </div>
</div>
<div class="container-fluid fh5co_footer_right_reserved">
    <div class="container">
        <div class="row  ">
            <div class="col-12 col-md-6 py-4 Reserved"> © Copyright 2018, All rights reserved. Design by <a href="https://freehtml5.co" title="Free HTML5 Bootstrap templates">FreeHTML5.co</a>. </div>
            <div class="col-12 col-md-6 spdp_right py-4">
                <a href="{% url 'blog:home' %}" class="footer_last_part_menu">Home</a>
                <a href="{% url 'blog:random_article' %}" class="footer_last_part_menu">Random</a>
                <a href="{% url 'blog:search' %}" class="footer_last_part_menu">Search</a>
                </div>
        </div>
    </div>
</div>

<div class="gototop js-top">
    <a href="#" class="js-gotop"><i class="fa fa-arrow-up"></i></a>
</div>

templates/includes/_header.html
{% load static %}
{% load tags %}
{% load tz %}
{% header_date as today %}

<div class="container-fluid fh5co_header_bg">
    <div class="container">
        <div class="row">
            <div class="col-12 fh5co_mediya_center"><a href="{% url 'blog:home' %}" class="color_fff fh5co_mediya_setting"><i
                    class="fa fa-clock-o"></i>&nbsp;&nbsp;&nbsp;{{ today|date:"l d M Y" }}</a>
                <a href="{% url 'blog:home' %}" class="color_fff fh5co_mediya_setting">News by Ilich</a>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-3 fh5co_padding_menu">
                <a href="{% url 'blog:home' %}">
                <img src="{% static 'images/logo.png' %}" alt="img" class="fh5co_logo_width"/></a>
            </div>
            <div class="col-12 col-md-9 align-self-center fh5co_mediya_right">
                <div class="text-center d-inline-block">
                    <a href="{% url 'blog:search' %}" class="fh5co_display_table"><div class="fh5co_verticle_middle"><i class="fa fa-search"></i></div></a>
                </div>
{#                <div class="text-center d-inline-block">#}
{#                    <a class="fh5co_display_table"><div class="fh5co_verticle_middle"><i class="fa fa-google-plus"></i></div></a>#}
{#                </div>#}
                <div class="text-center d-inline-block">
                    <a href="https://twitter.com/fh5co" target="_blank" class="fh5co_display_table"><div class="fh5co_verticle_middle"><i class="fa fa-twitter"></i></div></a>
                </div>
                <div class="text-center d-inline-block">
                    <a href="https://fb.com/fh5co" target="_blank" class="fh5co_display_table"><div class="fh5co_verticle_middle"><i class="fa fa-facebook"></i></div></a>
                </div>
                <!--<div class="d-inline-block text-center"><img src="images/country.png" alt="img" class="fh5co_country_width"/></div>-->
{#                <div class="d-inline-block text-center dd_position_relative ">#}
{#                    <select class="form-control fh5co_text_select_option">#}
{#                        <option>English </option>#}
{#                        <option>French </option>#}
{#                        <option>German </option>#}
{#                        <option>Spanish </option>#}
{#                    </select>#}
{#                </div>#}
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>

templates/includes/_navbar.html
{% load static %}

<div class="container-fluid bg-faded fh5co_padd_mediya padding_786">
    <div class="container padding_786">
        <nav class="navbar navbar-toggleable-md navbar-light ">
            <button class="navbar-toggler navbar-toggler-right mt-3" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation"><span class="fa fa-bars"></span></button>
            <a class="navbar-brand" href="{% url 'blog:home' %}"><img src="{% static 'images/logo.png' %}" alt="img" class="mobile_logo_width"/></a>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav" style="display: flex; width: 100%; justify-content: space-between;">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:home' %}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" href="{% url 'blog:random_article' %}">Random <span class="sr-only">(current)</span></a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item ">
                            <a class="nav-link" href="{% url 'blog:create_article' %}">Create <span class="sr-only">(current)</span></a>
                        </li>
                    {% endif %}
{#                    <li class="nav-item dropdown">#}
{#                        <a class="nav-link dropdown-toggle" href="#" id="dropdownMenuButton2" data-toggle="dropdown"#}
{#                           aria-haspopup="true" aria-expanded="false">World <span class="sr-only">(current)</span></a>#}
{#                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink_1">#}
{#                            <a class="dropdown-item" href="#">Action in</a>#}
{#                            <a class="dropdown-item" href="#">Another action</a>#}
{#                            <a class="dropdown-item" href="#">Something else here</a>#}
{#                        </div>#}
{#                    </li>#}
{#                    <li class="nav-item dropdown">#}
{#                        <a class="nav-link dropdown-toggle" href="#" id="dropdownMenuButton3" data-toggle="dropdown"#}
{#                           aria-haspopup="true" aria-expanded="false">Community<span class="sr-only">(current)</span></a>#}
{#                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink_1">#}
{#                            <a class="dropdown-item" href="#">Action in</a>#}
{#                            <a class="dropdown-item" href="#">Another action</a>#}
{#                            <a class="dropdown-item" href="#">Something else here</a>#}
{#                        </div>#}
{#                    </li>#}
                    <ul class="navbar-nav" style="display: flex;  justify-content: space-between;">
                        <li class="nav-item ">
                            {% if user.is_authenticated %}
                                <a class="nav-link" href="{% url 'blog:home' %}">{{ user }} <span class="sr-only">(current)</span></a>
                                {% else %}
                                <a class="nav-link" href="{% url 'user:sign_up' %}">Sign Up <span class="sr-only">(current)</span></a>
                            {% endif %}
                        </li>
                        <li class="nav-item ">
                            {% if user.is_authenticated %}
                                <a class="nav-link" href="{% url 'user:logout' %}">Logout <span class="sr-only">(current)</span></a>
                                {% else %}
                                <a class="nav-link" href="{% url 'user:sign_in' %}">Sign In <span class="sr-only">(current)</span></a>
                            {% endif %}
                        </li>
                    </ul>
                </ul>
            </div>
        </nav>
    </div>
</div>